services:
  nodebb:
    image: ghcr.io/skynomads/nodebb:2.5.3
    depends_on:
      - db
    ports:
      - 8080:8080
    volumes:
      - uploads:/var/nodebb/uploads
    environment:
      NODEBB_URL: http://localhost
      NODEBB_PORT: "8080"
      NODEBB_DB: postgres
      NODEBB_DB_HOST: db
      NODEBB_DB_PORT: 5432
      NODEBB_DB_USER: nodebb
      NODEBB_DB_PASSWORD: nodebb
      NODEBB_DB_NAME: nodebb
      NODEBB_DB_SSL: "false"
      NODEBB_ADMIN_USERNAME: admin
      NODEBB_ADMIN_EMAIL: admin@example.com
      NODEBB_ADMIN_PASSWORD: password1337
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: nodebb
      POSTGRES_USER: nodebb
  adminer:
    image: adminer
    ports:
      - 8090:8080

volumes:
  uploads: