package:
  name: elvish
  version: 0.18.0
  epoch: 0
  description: Expressive Programming Language + Versatile Interactive Shell
  target-architecture:
    - all
  copyright:
    - paths:
      - "*"
      attestation: |
        Copyright (c) elvish developers and contributors, All rights reserved.
      license: BSD-2-Clause

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
      - https://dl-cdn.alpinelinux.org/alpine/edge/community
    packages:
      - alpine-baselayout-data
      - ca-certificates-bundle
      - busybox
      - go

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/elves/elvish/archive/refs/tags/v${{package.version}}.tar.gz
      expected-sha256: f4635db90af2241bfd37e17ac1a72567b92d18a396598da2099a908b3d88c590
  - runs: |
      mkdir -p "${{targets.destdir}}/usr/bin"
      go build -ldflags "-s" -o "${{targets.destdir}}/usr/bin/elvish" ./cmd/nodaemon/elvish
  - uses: strip