package:
  name: fider
  version: 0.21.1
  epoch: 0
  description: Open platform to collect and prioritize feedback
  target-architecture:
    - amd64
  copyright:
    - paths:
      - "*"
      license: AGPL-3.0-only
  dependencies:
    runtime:

environment:
  contents:
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - wolfi-baselayout
      - glibc
      - ca-certificates-bundle
      - busybox
      - make
      - gcc
      - build-base
      - go
      - nodejs
      - curl
      #- npm

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/getfider/fider/archive/refs/tags/v${{package.version}}.tar.gz
      expected-sha256: b981360d7017849e1efd0ae0970df6239a32ebdca2be35785b1208f1552fe99e
  - runs: |
      curl -L https://www.npmjs.com/install.sh | sh
      npm ci
      make build-server build-ssr build-ui
      mkdir -p "${{targets.destdir}}/usr/bin" "${{targets.destdir}}/usr/share/fider"
      cp -r migrations views locale favicon.png dist robots.txt ssr.js "${{targets.destdir}}/usr/share/fider"
      cp fider "${{targets.destdir}}/usr/bin"
  - uses: strip

# TODO no libyaml/crystal on wolfi
# subpackages:
#   - name: fider-entrypoint
#     dependencies:
#       runtime:
#         - litestream
#         - yaml
#         - sqlite
#     pipeline:
#       - runs: |
#           mkdir -p "${{targets.subpkgdir}}/usr/bin"
#           shards install
#           crystal build --release src/entrypoint/pocketbase.cr -o /usr/bin/entrypoint
#       - uses: strip