package:
  name: flarum
  version: 1.5.0
  epoch: 0
  description: Simple forum software for building great communities
  target-architecture:
    - all
  copyright:
    - paths:
      - "*"
      license: MIT
  dependencies:
    runtime:
      - composer
      - nginx

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
      - https://dl-cdn.alpinelinux.org/alpine/edge/community
    packages:
      - busybox
      - composer

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/benbjohnson/litestream/archive/refs/tags/v${{package.version}}.tar.gz
      expected-sha256: c30b85679a120fba2614574f98586d693639224683d585af2c02931fd285c2f9
  - runs: |
      mkdir -p "${{targets.destdir}}/srv/flarum"
      composer create-project flarum/flarum:${{package.version}} "${{targets.destdir}}/srv/flarum" --ignore-platform-reqs
  - uses: strip