package:
  name: flarum
  version: 1.5.0
  epoch: 0
  description: Simple forum software for building great communities
  target-architecture:
    - amd64
  copyright:
    - paths:
      - "*"
      license: MIT
  dependencies:
    runtime:
      - composer
      - nginx

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
      - https://dl-cdn.alpinelinux.org/alpine/edge/community
    packages:
      - alpine-baselayout
      - ca-certificates-bundle
      #- nginx-php
      - composer

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/flarum/flarum/archive/refs/tags/v${{package.version}}.tar.gz
      expected-sha256: b4d7592a7a02ba175b4d84ee3b440725633ff556dc65ee8cea21d0a759a63f4c
  - runs: |
      mkdir -p "${{targets.destdir}}/srv/flarum"
      #cp /etc/php8/php-fpm.d/www.conf "${{targets.destdir}}/srv/flarum"
      composer create-project flarum/flarum:${{package.version}} "${{targets.destdir}}/srv/flarum" --ignore-platform-reqs
  - uses: strip