package:
  name: litestream
  version: 0.3.9
  epoch: 0
  description: Streaming replication for SQLite
  target-architecture:
    - all
  copyright:
    - paths:
      - "*"
      license: Apache-2.0

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
      - https://dl-cdn.alpinelinux.org/alpine/edge/community
    packages:
      - alpine-baselayout-data
      - ca-certificates-bundle
      - busybox
      - go

pipeline:
  - uses: fetch
    with:
      uri: https://github.com/benbjohnson/litestream/archive/refs/tags/v${{package.version}}.tar.gz
      expected-sha256: c30b85679a120fba2614574f98586d693639224683d585af2c02931fd285c2f9
  - runs: |
      mkdir -p "${{targets.destdir}}/usr/bin"
      go build -ldflags "-s" -o "${{targets.destdir}}/usr/bin/litestream" ./cmd/litestream
  - uses: strip