package:
  name: nginx-php
  version: 0.1.0
  epoch: 0
  # description: ''
  target-architecture:
    - amd64
  # copyright:
  #   - paths:
  #     - "*"
  #     license: AGPL-3.0-only
  dependencies:
    runtime:
      - apache2-utils
      - git
      - logrotate
      - nano
      - nginx
      - openssl
      - php8
      - php8-fileinfo
      - php8-fpm
      - php8-json
      - php8-mbstring
      - php8-openssl
      - php8-session
      - php8-simplexml
      - php8-xml
      - php8-xmlwriter
      - php8-zlib

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
      - https://dl-cdn.alpinelinux.org/alpine/edge/community
    packages:
      - alpine-baselayout
      - ca-certificates-bundle

pipeline:
  - runs: |
      mkdir -p "${{targets.destdir}}"