package:
  name: pocketbase-entrypoint
  version: 0.1.0
  epoch: 0
  target-architecture:
    - all

environment:
  contents:
    repositories:
      - https://dl-cdn.alpinelinux.org/alpine/edge/main
    packages:
      - alpine-baselayout-data
      - busybox

pipeline:
  - runs: |
      mkdir -p "${{targets.destdir}}/usr/bin" "${{targets.destdir}}/etc"
      cp entrypoints/pocketbase/entrypoint.sh "${{targets.destdir}}/usr/bin"
      cp entrypoints/pocketbase/litestream.yml "${{targets.destdir}}/etc"