name: builder

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      version:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/skynomads/${{ inputs.image }}
          flavor: |
            latest=true
          tags: |
            type=ref,event=branch
            type=sha
          labels: |
            org.opencontainers.image.version=${{ inputs.version }}
      - name: Build and push ${{ inputs.image }}
        uses: docker/build-push-action@v2
        with:
          context: ${{ inputs.image }}
          push: true
          tags: ${{ steps.meta.outputs.tags }},ghcr.io/skynomads/${{ inputs.image }}:${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            VERSION=${{ inputs.version }}
