name: Build and publish

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 */2 * *"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Melange
        uses: chainguard-dev/actions/setup-melange@main
      - name: Setup Go
        uses: actions/setup-go@v3
      - name: Build packages
        run: |
          go install chainguard.dev/apko@latest
          sudo make packages
      - name: Publish packages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/packages
          target-folder: /packages/edge
      - name: Build and publish containers
        run: |
          apko login --username "${{ github.repository_owner }}" --password "${{ secrets.GITHUB_TOKEN }}" ghcr.io
          sudo env "PATH=$PATH" make publish