name: Build and publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chainguard-dev/actions/setup-melange@main
      - uses: actions/setup-go@v3
      - name: Login to GitHub registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          go install chainguard.dev/apko@latest
          sudo make packages
          sudo env "PATH=$PATH" make containers
          find ./dist/containers -type f -name "*.tar" -exec docker load --input "{}"  \;
          docker push --all-tags
